[phases.setup]
nixPkgs = ["php82", "curl", "nodejs-20_x"]

[phases.install]
cmds = [
  "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
  "chmod +x /usr/local/bin/composer",
  "cd bend && /usr/local/bin/composer install --no-dev --optimize-autoloader",
  "cd fend && npm install && npm run build"
]

[start]
cmd = "chmod +x start.sh && ./start.sh"

